version: 2

sources:
  - name: staging
    database: "{{ env_var('DBT_DATABASE', '<your GCP project>') }}"
    schema: "{{ env_var('DBT_SCHEMA', '<your Bigquery dataset>') }}"
      # loaded_at_field: record_loaded_at
    tables:
      - name: observation_external